#!/usr/bin/env ruby -W0
# frozen_string_literal: true

lib_path = File.dirname(__FILE__) + '/../lib'
$LOAD_PATH << lib_path if Dir.exist?(lib_path)

require 'colored2'
require 'dupervisor'
require 'awesome_print'

# rubocop: disable Style/StderrPuts
class Runner
  attr_reader :config

  def initialize(argv = ARGV.dup)
    @config = DuperVisor::CLI.new(argv).parse
  end

  def run!
    DuperVisor::Main.new(config).run
  rescue DuperVisor::CLIError => e
    warn "Usage error: #{e.message.bold.red}\n\n"
    DuperVisor::CLI.new(['--help']).parse
  rescue StandardError => e
    warn "Processing error: #{e.inspect}".bold.red
    if config&.trace
      shift = '    '
      warn shift + e.backtrace.join("\n#{shift}").bold
    end
  end

  private

  def warn(*msg)
    STDERR.puts msg.join("\n").bold.red
  end
end
# rubocop: enable Style/StderrPuts

Runner.new.run!
