#!/usr/bin/env ruby -W0
lib_path = File.dirname(__FILE__) + '/../lib'
if Dir.exist?(lib_path)
  $LOAD_PATH << lib_path
end
require 'colored2'
require 'dupervisor'
require 'awesome_print'

begin
  DuperVisor::Main.new(DuperVisor::CLI.new(ARGV).parse).run
rescue DuperVisor::CLIError => e
  STDERR.puts 'Usage error: ' + e.message.bold.red
  puts
  DuperVisor::CLI.new(['--help']).parse
end
